# .rustfmt.toml
#
# Code format definitions for the Rust Linux 'indistrial-io' crate.
#

edition = "2021"

# As of 2025-05-23, this is still unstable, requiring +nightly
control_brace_style = "ClosingNextLine"

