# Spell-check configuration for use with the Rust 'typos' utility app.
# ....because I really can't spell.
#
# See: https://crates.io/crates/typos
#

[default.extend-words]
thr = "thr"

# Don't bother checking the -sys crate. Too much jibberish.
[files]
extend-exclude = ["libiio-sys/*"]

